/*****************************************************************************
* Model: mega2560-qpn-doser.qm
* File:  ./aoEncoder.cpp
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::aoEncoder.cpp} ......................................................*/

//#include "qfn_port.h"
#include "qpn.h"
#include "board.h"
#include "activeObjects.h"

/*Q_DEFINE_THIS_FILE*/


/* Scale class declaration -----------------------------------------------*/
/*${components::aoEncoder} .................................................*/
typedef struct aoEncoder {
/* protected: */
    QActive super;
} aoEncoder;

/* protected: */
static QState aoEncoder_initial(aoEncoder * const me);
static QState aoEncoder_idle(aoEncoder * const me);


/* Global objects ----------------------------------------------------------*/
aoEncoder AO_Encoder;     /* the single instance of the Encoder active object */

/* Scale class definition ------------------------------------------------*/
/*${components::aoEncoder_constructor} .....................................*/
void aoEncoder_constructor(void) {
    QActive_ctor(&AO_Encoder.super, Q_STATE_CAST(&aoEncoder_initial));
}
/*${components::aoEncoder} .................................................*/
/*${components::aoEncoder::SM} .............................................*/
static QState aoEncoder_initial(aoEncoder * const me) {
    /* ${components::aoEncoder::SM::initial} */
    return Q_TRAN(&aoEncoder_idle);
}
/*${components::aoEncoder::SM::idle} .......................................*/
static QState aoEncoder_idle(aoEncoder * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* ${components::aoEncoder::SM::idle::ENCODER_INC} */
        case ENCODER_INC_SIG: {
            TargetDose += GRINDER_DOSE_STEP;
            BSP_displayDose(TargetDose);
            status_ = Q_TRAN(&aoEncoder_idle);
            break;
        }
        /* ${components::aoEncoder::SM::idle::ENCODER_DEC} */
        case ENCODER_DEC_SIG: {
            TargetDose -= GRINDER_DOSE_STEP;
            BSP_displayDose(TargetDose);
            status_ = Q_TRAN(&aoEncoder_idle);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

