/*****************************************************************************
* Model: mega2560-qpn-doser.qm
* File:  ./aoWeight.cpp
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::aoWeight.cpp} .......................................................*/

//#include "qfn_port.h"
#include "qpn.h"
#include "board.h"
#include "activeObjects.h"

/*Q_DEFINE_THIS_FILE*/


/* Scale class declaration -----------------------------------------------*/
/*${components::aoWeight} ..................................................*/
typedef struct aoWeight {
/* protected: */
    QActive super;
} aoWeight;

/* protected: */
static QState aoWeight_initial(aoWeight * const me);
static QState aoWeight_state1(aoWeight * const me);


/* Global objects ----------------------------------------------------------*/
aoWeight AO_Weight;     /* the single instance of the Weight active object */

/* Scale class definition ------------------------------------------------*/
/*${components::aoWeight_constructor} ......................................*/
void aoWeight_constructor(void) {
    QActive_ctor(&AO_Weight.super, Q_STATE_CAST(&aoWeight_initial));
}
/*${components::aoWeight} ..................................................*/
/*${components::aoWeight::SM} ..............................................*/
static QState aoWeight_initial(aoWeight * const me) {
    /* ${components::aoWeight::SM::initial} */
    return Q_TRAN(&aoWeight_state1);
}
/*${components::aoWeight::SM::state1} ......................................*/
static QState aoWeight_state1(aoWeight * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

